import { PurchaseOrder } from '../types/po';
import { MaterialRate, ProcessRate, MultipliersConfig, HsnGstRule } from '../types/rates';
import { QuotationDocument } from '../types/quotation';
import { Customer } from '../types/customer';
import { PlantSettings } from '../types/settings';

export const mockMaterialRates: MaterialRate[] = [
  {
    id: 'mat-01',
    gradeAndSpec: 'Cast Iron (CI Grade 2 / FG 260)',
    subSpec: 'IS: 210 FG 260 • Tensile: 260 MPa',
    category: 'Ferrous',
    baseRatePerKg: 95.00,
    scrapCreditPerKg: 32.00,
    densityGPerCm3: 7.20,
    primarySupplier: 'Kirloskar Ferrous',
    mandiHub: 'Solapur Road Depot',
    aiMatchStatus: 'VERIFIED',
    lastUpdated: '12 Aug 2026',
    isPopular: true
  },
  {
    id: 'mat-02',
    gradeAndSpec: 'Steel EN8 (Alloy Hardened)',
    subSpec: 'BS 970 • Medium Carbon • Bright Drawn',
    category: 'Ferrous',
    baseRatePerKg: 110.00,
    scrapCreditPerKg: 38.00,
    densityGPerCm3: 7.85,
    primarySupplier: 'Kalyani Steels',
    mandiHub: 'Pune MCX Stock',
    aiMatchStatus: 'VERIFIED',
    lastUpdated: '14 Aug 2026',
    isPopular: true
  },
  {
    id: 'mat-03',
    gradeAndSpec: 'Mild Steel (IS 2062 Grade E250)',
    subSpec: 'IS 2062:2011 • Structural Laser Plate',
    category: 'Ferrous',
    baseRatePerKg: 68.00,
    scrapCreditPerKg: 26.00,
    densityGPerCm3: 7.85,
    primarySupplier: 'SAIL Yards',
    mandiHub: 'Kalamboli Steel Exchange',
    aiMatchStatus: 'VERIFIED',
    lastUpdated: '15 Aug 2026',
    isPopular: true
  },
  {
    id: 'mat-04',
    gradeAndSpec: 'Stainless Steel SS 304 (Austenitic)',
    subSpec: 'ASTM A240 • Food & Chemical Grade',
    category: 'Non-Ferrous',
    baseRatePerKg: 218.00,
    scrapCreditPerKg: 85.00,
    densityGPerCm3: 8.00,
    primarySupplier: 'Jindal Stainless',
    mandiHub: 'Mumbai Metal Exchange',
    aiMatchStatus: 'VERIFIED',
    lastUpdated: '10 Aug 2026',
    isPopular: false
  },
  {
    id: 'mat-05',
    gradeAndSpec: 'Aluminum 6061-T6 (Extruded Alloy)',
    subSpec: 'AMS 4027 • Aircraft Structural',
    category: 'Alloys',
    baseRatePerKg: 245.00,
    scrapCreditPerKg: 110.00,
    densityGPerCm3: 2.70,
    primarySupplier: 'Hindalco Industries',
    mandiHub: 'Belgaum Smelter Hub',
    aiMatchStatus: 'VERIFIED',
    lastUpdated: '08 Aug 2026',
    isPopular: false
  },
  {
    id: 'mat-06',
    gradeAndSpec: 'Brass CuZn39Pb3 (Free Cutting)',
    subSpec: 'CW614N • High Precision Turned Pinion',
    category: 'Non-Ferrous',
    baseRatePerKg: 485.00,
    scrapCreditPerKg: 290.00,
    densityGPerCm3: 8.40,
    primarySupplier: 'Jamnagar Brass Exchange',
    mandiHub: 'Gujarat NCDEX Hub',
    aiMatchStatus: 'VERIFIED',
    lastUpdated: '05 Aug 2026',
    isPopular: false
  }
];

export const mockProcessRates: ProcessRate[] = [
  {
    id: 'proc-01',
    workstationName: 'CNC 4-Axis Machining Center',
    code: 'VMC-4X-01',
    category: 'CNC',
    hourlyRate: 550,
    setupCost: 800,
    capacityUtilizationPct: 82,
    shiftMode: '2 Shifts / Day',
    lastCalibrated: '01 Sep 2026'
  },
  {
    id: 'proc-02',
    workstationName: 'CNC Precision Turning Center',
    code: 'TNC-2600',
    category: 'Turning',
    hourlyRate: 420,
    setupCost: 500,
    capacityUtilizationPct: 76,
    shiftMode: '2 Shifts / Day',
    lastCalibrated: '28 Aug 2026'
  },
  {
    id: 'proc-03',
    workstationName: 'Centerless & Cylindrical Grinding',
    code: 'GRD-500',
    category: 'Grinding',
    hourlyRate: 280,
    setupCost: 350,
    capacityUtilizationPct: 65,
    shiftMode: '1 Shift / Day',
    lastCalibrated: '15 Aug 2026'
  },
  {
    id: 'proc-04',
    workstationName: 'Fiber Laser Cutting (4kW High Speed)',
    code: 'LSR-4000',
    category: 'Laser & Fabrication',
    hourlyRate: 650,
    setupCost: 400,
    capacityUtilizationPct: 88,
    shiftMode: '3 Shifts / 24h',
    lastCalibrated: '02 Sep 2026'
  }
];

export const mockMultipliersConfig: MultipliersConfig = {
  factoryOverheadPct: 12.0,
  commercialProfitMarginPct: 15.0,
  scrapSurchargePct: 4.5,
  defaultGstPct: 18.0,
  mandiLinkStatus: 'MCX / NCDEX Daily Sync OK (06:30 AM IST)',
  lastMandiSync: 'Today at 06:30 AM IST'
};

export const mockHsnRules: HsnGstRule[] = [
  { chapter: '84', hsnCode: '84139190', description: 'Parts of Pumps for Liquids (Cast Iron)', cgstPct: 9, sgstPct: 9, igstPct: 18, isDefault: true },
  { chapter: '84', hsnCode: '84831099', description: 'Transmission Shafts & Cranks (Steel EN8)', cgstPct: 9, sgstPct: 9, igstPct: 18, isDefault: true },
  { chapter: '73', hsnCode: '73269099', description: 'Other Articles of Iron or Steel (Cover Plates)', cgstPct: 9, sgstPct: 9, igstPct: 18, isDefault: true },
  { chapter: '87', hsnCode: '87082900', description: 'Parts and Accessories of Motor Vehicles', cgstPct: 9, sgstPct: 9, igstPct: 18, isDefault: false }
];

export const mockSamplePurchaseOrder: PurchaseOrder = {
  id: 'po-441',
  originalFileName: 'Mahindra_Agro_PO_441.pdf',
  fileSizeBytes: 248 * 1024,
  totalPages: 2,
  uploadTimestamp: '15 Sep 2026, 10:14 AM',
  confidenceScore: 96.4,
  status: 'NEEDS_REVIEW',
  metadata: {
    name: 'Mahindra Precision Agro Pvt Ltd',
    gstin: '27AAAPM8891C1Z4',
    poNumber: 'PO-2026-441',
    poDate: '15 Sep 2026',
    deliveryDueDate: '30 Sep 2026',
    billingAddress: 'Plot 42, MIDC Bhosari Industrial Area, Pune 411026, Maharashtra',
    contactPerson: 'Mr. Vikram Patil',
    email: 'procurement.agro@mahindra.com',
    phone: '+91 98224 81902'
  },
  items: [
    {
      id: 'item-01',
      sNo: '01',
      itemDescription: 'Pump Casing',
      hsnCode: '84139190',
      drawingCode: 'BPE-PC-402 Rev 03',
      extractedSpecification: 'CI Grade 2 (Cast Iron)',
      rateCardMatch: 'Cast Iron @ ₹95/kg + Machining',
      rateCardMatchStatus: 'VERIFIED',
      quantity: 10,
      unit: 'Nos',
      grossWeightKg: 45,
      scrapWeightKg: 12,
      machiningHours: 1.8
    },
    {
      id: 'item-02',
      sNo: '02',
      itemDescription: 'Shaft',
      hsnCode: '84831099',
      drawingCode: 'MA-SFT-884-D',
      extractedSpecification: 'EN8 Steel Alloy (Hardened)',
      rateCardMatch: 'Steel EN8 @ ₹110/kg + Turning',
      rateCardMatchStatus: 'VERIFIED',
      quantity: 5,
      unit: 'Nos',
      grossWeightKg: 18,
      scrapWeightKg: 4,
      machiningHours: 1.2
    },
    {
      id: 'item-03',
      sNo: '03',
      itemDescription: 'Cover Plate',
      hsnCode: '73269099',
      drawingCode: 'BPE-CP-101',
      extractedSpecification: 'Mild Steel (IS 2062 Grade)',
      rateCardMatch: 'Select Grade...',
      rateCardMatchStatus: 'AMBIGUOUS',
      ambiguityReason: 'Item #3 \'Cover Plate\' has ambiguous tensile grade in customer PO specification.',
      selectedGrade: '',
      quantity: 20,
      unit: 'Nos',
      grossWeightKg: 12,
      scrapWeightKg: 2,
      machiningHours: 0.6
    }
  ],
  leadTimeDays: 15,
  taxComplianceNote: 'Maharashtra (27) to Maharashtra (27) — CGST 9% + SGST 9% configured automatically.',
  rawMaterialIndexNote: 'Market spot prices synchronized today at 09:30 AM IST'
};

export const mockQuotationsList: QuotationDocument[] = [
  {
    id: 'qt-089',
    quotationNumber: 'QT-2026-089',
    version: 'v1.0',
    createdAt: '18 Aug 2026',
    validUntil: '15 Oct 2026',
    poReference: 'PO-2026-441',
    poDate: '15 Aug 2026',
    customer: {
      name: 'Mahindra Precision Agro Pvt Ltd',
      gstin: '27AAACM1234F1Z5',
      poNumber: 'PO-2026-441',
      poDate: '15 Aug 2026',
      deliveryDueDate: '30 Sep 2026',
      billingAddress: 'Plant 4, MIDC Butibori Industrial Zone, Nagpur - 441108, Maharashtra',
      contactPerson: 'Mr. Vikram Patil (Head of Sourcing)',
      phone: '+91 98224 81902',
      email: 'procurement.agro@mahindra.com'
    },
    status: 'SENT',
    calculation: {
      materialCost: 45000,
      processCost: 18500,
      baseSubtotal: 63500,
      overheadPct: 12,
      overheadAmount: 7620,
      profitMarginPct: 15,
      profitAmount: 10668,
      taxableValue: 81788,
      isInterstate: false,
      cgstPct: 9,
      cgstAmount: 7361,
      sgstPct: 9,
      sgstAmount: 7361,
      igstPct: 0,
      igstAmount: 0,
      totalGstAmount: 14722,
      grandTotal: 96510,
      grandTotalInWords: 'INR Ninety-Six Thousand Five Hundred and Ten Only',
      roundingAdjustment: 0
    },
    itemCostings: [
      {
        itemId: 'item-01',
        itemDescription: 'Cast Iron Pump Casing (CI-25)',
        quantity: 10,
        unit: 'Nos',
        materialName: 'Cast Iron (CI Grade 2 / FG 260)',
        grossWeightKg: 45,
        materialRatePerKg: 95,
        grossMaterialCost: 42750,
        scrapWeightKg: 12,
        scrapCreditPerKg: 32,
        scrapCreditTotal: 3840,
        netMaterialCost: 38910,
        workstationName: 'CNC 4-Axis Machining Center',
        machiningHours: 1.8,
        hourlyRate: 550,
        setupCost: 800,
        processCost: 10700,
        itemSubtotal: 49610,
        unitPrice: 4961
      },
      {
        itemId: 'item-02',
        itemDescription: 'CNC Turned Precision Drive Shaft',
        quantity: 5,
        unit: 'Nos',
        materialName: 'Steel EN8 (Alloy Hardened)',
        grossWeightKg: 18,
        materialRatePerKg: 110,
        grossMaterialCost: 9900,
        scrapWeightKg: 4,
        scrapCreditPerKg: 38,
        scrapCreditTotal: 760,
        netMaterialCost: 9140,
        workstationName: 'CNC Precision Turning Center',
        machiningHours: 1.2,
        hourlyRate: 420,
        setupCost: 500,
        processCost: 3020,
        itemSubtotal: 12160,
        unitPrice: 2432
      },
      {
        itemId: 'item-03',
        itemDescription: 'Precision Flanged Cover Plate (Laser Cut)',
        quantity: 20,
        unit: 'Nos',
        materialName: 'Mild Steel (IS 2062 Grade E250)',
        grossWeightKg: 12,
        materialRatePerKg: 68,
        grossMaterialCost: 16320,
        scrapWeightKg: 2,
        scrapCreditPerKg: 26,
        scrapCreditTotal: 1040,
        netMaterialCost: 15280,
        workstationName: 'Fiber Laser Cutting (4kW)',
        machiningHours: 0.6,
        hourlyRate: 650,
        setupCost: 400,
        processCost: 8200,
        itemSubtotal: 23480,
        unitPrice: 1174
      }
    ],
    boqItems: mockSamplePurchaseOrder.items,
    leadTimeDays: 14,
    deliveryTerms: 'Ex-Works Bhosari / FOB Chakan',
    paymentTerms: '30 Days Net from date of invoice / Dispatch',
    freightTerms: 'Borne by customer via approved transporter',
    warrantyClause: '12 Months against manufacturing & casting defects',
    primaryContactPerson: 'Vikram Patil',
    primaryContactPhone: '+91 98224 81902',
    primaryContactEmail: 'procurement.agro@mahindra.com',
    pdfFileSizeKb: 248,
    auditTrail: [
      { id: 'aud-1', timestamp: '18 Aug, 10:14 AM', title: 'PO Uploaded & OCR Parsed', actor: 'R. Deshmukh (Production)', status: 'COMPLETED', description: 'OCR model v4.2 verified 100%' },
      { id: 'aud-2', timestamp: '18 Aug, 10:19 AM', title: 'Automated Costing & HSN Verification', actor: 'Deterministic Engine v2.4', status: 'COMPLETED', description: 'All rate cards locked to Mandi index' },
      { id: 'aud-3', timestamp: '18 Aug, 10:24 AM', title: 'Margin Approved by Plant Manager', actor: 'Rajesh Sharma (Plant Head)', status: 'COMPLETED', description: 'Signed digitally (Token #910)' },
      { id: 'aud-4', timestamp: '18 Aug, 10:28 AM', title: 'Dispatched via WhatsApp & Email', actor: 'System Gateway', status: 'COMPLETED', description: 'Delivered & Read by Vikram Patil' }
    ]
  },
  {
    id: 'qt-088',
    quotationNumber: 'QT-2026-088',
    version: 'v2.1',
    createdAt: '17 Aug 2026',
    validUntil: '17 Oct 2026',
    poReference: 'PD-2026-8902',
    poDate: '16 Aug 2026',
    customer: {
      name: 'Tata Motors Commercial',
      gstin: '27AAACT2727Q1ZW',
      poNumber: 'PD-2026-8902',
      poDate: '16 Aug 2026',
      deliveryDueDate: '10 Oct 2026',
      billingAddress: 'Pimpri Works, Pune 411018'
    },
    status: 'READY',
    calculation: {
      materialCost: 215000,
      processCost: 139000,
      baseSubtotal: 354661,
      overheadPct: 10,
      overheadAmount: 35466,
      profitMarginPct: 12,
      profitAmount: 46815,
      taxableValue: 354661,
      isInterstate: false,
      cgstPct: 9,
      cgstAmount: 31920,
      sgstPct: 9,
      sgstAmount: 31920,
      igstPct: 0,
      igstAmount: 0,
      totalGstAmount: 63839,
      grandTotal: 418500,
      grandTotalInWords: 'INR Four Lakh Eighteen Thousand Five Hundred Only',
      roundingAdjustment: 0
    },
    itemCostings: [],
    boqItems: [],
    leadTimeDays: 21,
    deliveryTerms: 'Door Delivery Pimpri',
    paymentTerms: '45 Days Net',
    freightTerms: 'Included',
    warrantyClause: 'Standard OEM Warranty',
    primaryContactPerson: 'Anand Kulkarni',
    primaryContactPhone: '+91 98230 11223',
    primaryContactEmail: 'a.kulkarni@tatamotors.com',
    pdfFileSizeKb: 512,
    auditTrail: []
  },
  {
    id: 'qt-087',
    quotationNumber: 'QT-2026-087',
    version: 'v1.2',
    createdAt: '16 Aug 2026',
    validUntil: '16 Oct 2026',
    poReference: 'LT-PO-9912',
    poDate: '15 Aug 2026',
    customer: {
      name: 'Larsen & Toubro Heavy',
      gstin: '24AAACL0149G1Z0',
      poNumber: 'LT-PO-9912',
      poDate: '15 Aug 2026',
      deliveryDueDate: '15 Nov 2026',
      billingAddress: 'Hazira Manufacturing Complex, Surat, Gujarat'
    },
    status: 'SENT',
    calculation: {
      materialCost: 890000,
      processCost: 669322,
      baseSubtotal: 1559322,
      overheadPct: 12,
      overheadAmount: 187118,
      profitMarginPct: 15,
      profitAmount: 261966,
      taxableValue: 1559322,
      isInterstate: true,
      cgstPct: 0,
      cgstAmount: 0,
      sgstPct: 0,
      sgstAmount: 0,
      igstPct: 18,
      igstAmount: 280678,
      totalGstAmount: 280678,
      grandTotal: 1840000,
      grandTotalInWords: 'INR Eighteen Lakh Forty Thousand Only',
      roundingAdjustment: 0
    },
    itemCostings: [],
    boqItems: [],
    leadTimeDays: 30,
    deliveryTerms: 'Hazira Port Delivery',
    paymentTerms: '60 Days LC',
    freightTerms: 'Excluded',
    warrantyClause: '24 Months Heavy Engineering Warranty',
    primaryContactPerson: 'Suresh Mehta',
    primaryContactPhone: '+91 98450 99887',
    primaryContactEmail: 'suresh.m@larsentoubro.com',
    pdfFileSizeKb: 1100,
    auditTrail: []
  },
  {
    id: 'qt-086',
    quotationNumber: 'QT-2026-086',
    version: 'v1.0',
    createdAt: '15 Aug 2026',
    validUntil: '15 Oct 2026',
    poReference: 'GA-RFQ-772',
    poDate: '14 Aug 2026',
    customer: {
      name: 'Godrej Aerospace Div',
      gstin: '27AAACG0563P1ZL',
      poNumber: 'GA-RFQ-772',
      poDate: '14 Aug 2026',
      deliveryDueDate: '20 Oct 2026',
      billingAddress: 'Vikhroli, Mumbai 400079'
    },
    status: 'REVISION_ISSUED',
    calculation: {
      materialCost: 380000,
      processCost: 265762,
      baseSubtotal: 645762,
      overheadPct: 14,
      overheadAmount: 90406,
      profitMarginPct: 18,
      profitAmount: 132510,
      taxableValue: 645762,
      isInterstate: false,
      cgstPct: 9,
      cgstAmount: 58118,
      sgstPct: 9,
      sgstAmount: 58118,
      igstPct: 0,
      igstAmount: 0,
      totalGstAmount: 116238,
      grandTotal: 762800,
      grandTotalInWords: 'INR Seven Lakh Sixty-Two Thousand Eight Hundred Only',
      roundingAdjustment: 0
    },
    itemCostings: [],
    boqItems: [],
    leadTimeDays: 25,
    deliveryTerms: 'Ex-Works Pune',
    paymentTerms: '30 Days Net',
    freightTerms: 'Customer Transporter',
    warrantyClause: 'Aerospace AS9100 Certificate of Conformance',
    primaryContactPerson: 'Meera Deshpande',
    primaryContactPhone: '+91 98200 44556',
    primaryContactEmail: 'm.deshpande@godrej.com',
    pdfFileSizeKb: 180,
    auditTrail: []
  },
  {
    id: 'qt-085',
    quotationNumber: 'QT-2026-085',
    version: 'v1.0',
    createdAt: '14 Aug 2026',
    validUntil: '14 Oct 2026',
    poReference: 'KOEL-P-3341',
    poDate: '13 Aug 2026',
    customer: {
      name: 'Kirloskar Oil Engines',
      gstin: '27AAACK1010A1ZP',
      poNumber: 'KOEL-P-3341',
      poDate: '13 Aug 2026',
      deliveryDueDate: '05 Oct 2026',
      billingAddress: 'Khadki, Pune 411003'
    },
    status: 'DRAFT',
    calculation: {
      materialCost: 160000,
      processCost: 116101,
      baseSubtotal: 276101,
      overheadPct: 12,
      overheadAmount: 33132,
      profitMarginPct: 15,
      profitAmount: 46385,
      taxableValue: 276101,
      isInterstate: false,
      cgstPct: 9,
      cgstAmount: 24849,
      sgstPct: 9,
      sgstAmount: 24849,
      igstPct: 0,
      igstAmount: 0,
      totalGstAmount: 49699,
      grandTotal: 325800,
      grandTotalInWords: 'INR Three Lakh Twenty-Five Thousand Eight Hundred Only',
      roundingAdjustment: 0
    },
    itemCostings: [],
    boqItems: [],
    leadTimeDays: 18,
    deliveryTerms: 'Ex-Works Pune',
    paymentTerms: '30 Days',
    freightTerms: 'Customer Scope',
    warrantyClause: 'Standard Warranty',
    primaryContactPerson: 'Ramesh Joshi',
    primaryContactPhone: '+91 98222 33445',
    primaryContactEmail: 'r.joshi@kirloskar.com',
    pdfFileSizeKb: 310,
    auditTrail: []
  },
  {
    id: 'qt-084',
    quotationNumber: 'QT-2026-084',
    version: 'v2.0',
    createdAt: '12 Aug 2026',
    validUntil: '12 Oct 2026',
    poReference: 'BF-PO-1109',
    poDate: '11 Aug 2026',
    customer: {
      name: 'Bharat Forge Ltd',
      gstin: '27AAACB2233M1Z2',
      poNumber: 'BF-PO-1109',
      poDate: '11 Aug 2026',
      deliveryDueDate: '30 Oct 2026',
      billingAddress: 'Mundhwa, Pune 411036'
    },
    status: 'ACCEPTED',
    calculation: {
      materialCost: 650000,
      processCost: 447033,
      baseSubtotal: 1097033,
      overheadPct: 10,
      overheadAmount: 109703,
      profitMarginPct: 12,
      profitAmount: 144808,
      taxableValue: 1097033,
      isInterstate: false,
      cgstPct: 9,
      cgstAmount: 98733,
      sgstPct: 9,
      sgstAmount: 98733,
      igstPct: 0,
      igstAmount: 0,
      totalGstAmount: 197467,
      grandTotal: 1294500,
      grandTotalInWords: 'INR Twelve Lakh Ninety-Four Thousand Five Hundred Only',
      roundingAdjustment: 0
    },
    itemCostings: [],
    boqItems: [],
    leadTimeDays: 20,
    deliveryTerms: 'Mundhwa Gate Delivery',
    paymentTerms: '30 Days Net',
    freightTerms: 'Included',
    warrantyClause: '18 Months',
    primaryContactPerson: 'Pravin Shinde',
    primaryContactPhone: '+91 98220 99112',
    primaryContactEmail: 'pravin.shinde@bharatforge.com',
    pdfFileSizeKb: 440,
    auditTrail: []
  }
];

export const mockCustomersList: Customer[] = [
  {
    id: 'cust-01',
    name: 'Mahindra Precision Agro Pvt Ltd',
    code: 'CUST-MAH-01',
    tradeName: 'Mahindra Agro Division',
    gstin: '27AAAPM8891C1Z4',
    pan: 'AAAPM8891C',
    contactPerson: 'Mr. Vikram Patil',
    designation: 'Head of Sourcing & Procurement',
    phone: '+91 98224 81902',
    email: 'procurement.agro@mahindra.com',
    billingAddress: 'Plot 42, MIDC Bhosari Industrial Area, Pune 411026, Maharashtra',
    shippingAddress: 'Plant 4, MIDC Butibori Industrial Zone, Nagpur - 441108, Maharashtra',
    state: 'Maharashtra',
    stateCode: '27',
    activeQuotationsCount: 2,
    totalQuotationsCount: 24,
    lifetimeValueInr: 4850000,
    creditDays: 30,
    rating: 'A+ Tier 1',
    lastQuotedDate: '18 Aug 2026'
  },
  {
    id: 'cust-02',
    name: 'Tata Motors Commercial',
    code: 'CUST-TAT-02',
    tradeName: 'Tata Motors CVBU',
    gstin: '27AAACT2727Q1ZW',
    pan: 'AAACT2727Q',
    contactPerson: 'Anand Kulkarni',
    designation: 'Sr. Purchase Manager',
    phone: '+91 98230 11223',
    email: 'a.kulkarni@tatamotors.com',
    billingAddress: 'Pimpri Works, Pune 411018, Maharashtra',
    shippingAddress: 'Pimpri Central Stores, Gate 3, Pune 411018',
    state: 'Maharashtra',
    stateCode: '27',
    activeQuotationsCount: 3,
    totalQuotationsCount: 52,
    lifetimeValueInr: 12400000,
    creditDays: 45,
    rating: 'Strategic OEM',
    lastQuotedDate: '17 Aug 2026'
  },
  {
    id: 'cust-03',
    name: 'Larsen & Toubro Heavy',
    code: 'CUST-LT-03',
    tradeName: 'L&T Heavy Engineering',
    gstin: '24AAACL0149G1Z0',
    pan: 'AAACL0149G',
    contactPerson: 'Suresh Mehta',
    designation: 'General Manager Procurement',
    phone: '+91 98450 99887',
    email: 'suresh.m@larsentoubro.com',
    billingAddress: 'Hazira Manufacturing Complex, Surat 394510, Gujarat',
    shippingAddress: 'Heavy Fabrication Shop Bay 7, Hazira, Gujarat',
    state: 'Gujarat',
    stateCode: '24',
    activeQuotationsCount: 1,
    totalQuotationsCount: 18,
    lifetimeValueInr: 28900000,
    creditDays: 60,
    rating: 'A+ Tier 1',
    lastQuotedDate: '16 Aug 2026'
  },
  {
    id: 'cust-04',
    name: 'Godrej Aerospace Div',
    code: 'CUST-GOD-04',
    tradeName: 'Godrej Precision Systems',
    gstin: '27AAACG0563P1ZL',
    pan: 'AAACG0563P',
    contactPerson: 'Meera Deshpande',
    designation: 'Aerospace Vendor Development',
    phone: '+91 98200 44556',
    email: 'm.deshpande@godrej.com',
    billingAddress: 'Plant 14, Pirojshanagar, Vikhroli, Mumbai 400079',
    shippingAddress: 'Plant 14 Aerospace Gate, Vikhroli, Mumbai',
    state: 'Maharashtra',
    stateCode: '27',
    activeQuotationsCount: 1,
    totalQuotationsCount: 14,
    lifetimeValueInr: 9800000,
    creditDays: 30,
    rating: 'Aerospace Class A',
    lastQuotedDate: '15 Aug 2026'
  },
  {
    id: 'cust-05',
    name: 'Bharat Forge Ltd',
    code: 'CUST-BFL-05',
    tradeName: 'Bharat Forge Component Works',
    gstin: '27AAACB2233M1Z2',
    pan: 'AAACB2233M',
    contactPerson: 'Pravin Shinde',
    designation: 'Vendor Quality & Commercial Head',
    phone: '+91 98220 99112',
    email: 'pravin.shinde@bharatforge.com',
    billingAddress: 'Mundhwa, Pune Cantonment, Pune 411036',
    shippingAddress: 'Machined Components Division, Mundhwa, Pune',
    state: 'Maharashtra',
    stateCode: '27',
    activeQuotationsCount: 2,
    totalQuotationsCount: 41,
    lifetimeValueInr: 16700000,
    creditDays: 30,
    rating: 'Key Partner',
    lastQuotedDate: '12 Aug 2026'
  }
];

export const mockPlantSettings: PlantSettings = {
  registeredName: 'Bharat Precision Engineering Pvt Ltd',
  tradeName: 'Precision Machining & Fabrication Division',
  plantAddress: 'Plot 42, MIDC Bhosari Industrial Area, Pune 411026, Maharashtra, India',
  isCorporateOfficeSame: true,
  panNumber: 'AABCB2018Q',
  cinNumber: 'U29299PN2018PTC17',
  udyamNumber: 'UDYAM-MH-26-00481',
  dispatchEmail: 'quotations@bharatprecision.co.in',
  commercialPhone: '+91 20 6712 9000',
  accreditations: ['ISO 9001:2015', 'IATF 16949:2016 Compliant'],

  gstHubs: [
    {
      id: 'hub-1',
      stateCode: '27',
      stateName: 'Maharashtra',
      gstin: '27AABCB2018Q1Z2',
      hubName: 'Bhosari Unit I (Primary Hub)',
      isPrimary: true,
      status: 'LIVE_AND_VALID'
    },
    {
      id: 'hub-2',
      stateCode: '24',
      stateName: 'Gujarat',
      gstin: '24AABCB2018Q1Z5',
      hubName: 'Sanand Tooling & Jigs Center',
      isPrimary: false,
      status: 'LIVE_AND_VALID'
    }
  ],
  eInvoicingAutoSync: true,
  reverseChargeMechanismDefault: false,

  prefixCode: 'BPE/QT/',
  fiscalYearSchema: '2024-25 (Standard)',
  sequentialPaddingDigits: 3,
  currentSequenceNumber: 90,
  autoResetYearly: true,

  logoFileName: 'bpe_vector_logo.svg',
  signatoryName: 'Rajesh Sharma',
  signatoryTitle: 'Plant Head & Director',
  signatoryStampFileName: 'Rajesh_Sharma_Seal.png',
  autoStampFinalized: true,
  letterheadAccentStyle: 'Slate Solid',

  bankName: 'State Bank of India',
  branchName: 'MIDC Bhosari, Pune',
  accountNumber: '38920194821',
  ifscCode: 'SBIN0004128',
  upiId: 'bpe.pune@sbi',

  deliveryTimeline: '14 to 21 Working Days from PO clearance',
  paymentTerms: '30 Days net from date of invoice / Dispatch',
  freightTerms: 'Ex-Works Pune / FOB Chakan',
  quotationValidity: '30 Days from date',
  qualityClause: 'Subject to final inspection at customer plant',

  activeTemplatePreset: 'Classic Industrial',
  headerAlignment: 'Left Logo + Right Legal Details',
  documentTitleBanner: 'FORMAL COMMERCIAL QUOTATION',
  pricingDisplayMode: 'Blended Unit Rate Only',
  tableRowDensity: 'Standard (16px)',
  showHsnCode: true,
  showRawMaterialGrade: true,
  showProcessSplit: false,
  showDigitalSeal: true,
  showBankQrCode: true
};
